swagger: "2.0"
info:
  title: B2c Startup backend
  description: Contains all api's and api endpoints and their descriptions.
  version: 1.0
  contact: 
    email: azeemsayyad1652@gmail.com
  servers:
    -url: "http://localhost:4000/"
    description: This is a Local server

schemes: [http,https]

paths:
  "/get/allTradePersons":
      get:
        summary: Returns All Registered TradePersons
        responses: 
          200:
            description: success
            schema:
              type: array
              items:
                $ref: "#/components/schemas/tradePerson"
          400:
            description: failed

  "/auth/register":
    post:
      summary: register the user
      description: It takes user attributes and will be stored in database
      parameters:
      - in: body
        name: tradePerson
        schema:
          $ref: "#/components/schemas/tradePerson"
      responses:
        200:
          description: User Registered Successfully
          schema:
            $ref: "#/components/schemas/tradePerson"
        400:
          description: Error


components:
  schemas:
    tradePerson:
      type: object
      properties:
          name:
            type: string
          profession:
            type: array
            items:
              type: string
          experience:
            type: string
          contact:
            type: string
          about:
            type: string